module.exports = {
  local: {
    port: 4009, // assign your own port no
    logs: "dev",
    applicationUrl: "http://20.121.222.211/",
    apiUrl: "http://localhost:4009",
    emailPath: "./src/views",
    mongoUri: "mongodb://localhost:27017/emate_toolkit_production",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "email.alert@ics-global.in",
    SMTP_PASS: "Desire$gnr@T3",
    SMTP_FROM_NAME: "Emate",
    SMTP_FROM_EMAIL: "info@emate.com",
    uploadFilePath: "./src/public/upload/",
    uploadFileUrl: "http://localhost:4009/upload/",
    uploadHelpFileUrl: "http://localhost:4009/helpPage/",
    uploadHelpFilePath: "./src/public/helpModule/",
    excelFileUploadPath: "./src/public/excelFiles",
    uploadSampleFilePath: "./src/public/sampleFiles",
    reportFolderPath: "./src/public/reports",
    reportFileUrl: "http://localhost:4009/report/",
    sampleFileUrl: "http://localhost:4009/sampleFile/",
    networkComputationStaticHTMLFile: "./src/templates/networkComputationReportTemplate.html",
    networkComputationHighChartHTMLFile: "./src/templates/highChartNC.html",
    portRatorStaticHTMLFile: "./src/templates/portRatorReportTemplate.html",
    forecastHTMLFile: "./src/templates/forecast.html",
  },

  development: {
    port: 4009, // assign your own port no
    logs: "dev",
    applicationUrl: "http://20.121.222.211/",
    apiUrl: "http://emate.ics-global.in:64460",
    emailPath: "./src/views",
    mongoUri: "mongodb://localhost:27017/emate_toolkit_production",
    // mongoUri: "mongodb://emate:emate123@ec2-23-20-238-242.compute-1.amazonaws.com:27018/emate_toolkit?readPreference=primary&authMechanism=DEFAULT&authSource=admin",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "email.alert@ics-global.in",
    SMTP_PASS: "Desire$gnr@T3",
    SMTP_FROM_NAME: "Emate",
    SMTP_FROM_EMAIL: "info@emate.com",
    uploadFilePath: "/usr/src/app/src/public/upload/",
    uploadHelpFilePath: "/usr/src/app/src/public/helpModule/",
    uploadSampleFilePath: "/usr/src/app/src/public/sampleFiles",
    uploadFileUrl: "http://emate.ics-global.in:64460/upload/",
    uploadHelpFileUrl: "http://emate.ics-global.in:64460/helpPage/",
    excelFileUploadPath: "/usr/src/app/src/public/excelFiles",
    reportFolderPath: "./src/public/reports",
    reportFileUrl: "http://emate.ics-global.in:64460/report/",
    sampleFileUrl: "http://emate.ics-global.in:64460/sampleFile/",
    networkComputationStaticHTMLFile: "./src/templates/networkComputationReportTemplate.html",
    networkComputationHighChartHTMLFile: "./src/templates/highChartNC.html",
    portRatorStaticHTMLFile: "./src/templates/portRatorReportTemplate.html",
    forecastHTMLFile: "./src/templates/forecast.html",
  },

  staging: {
    port: 4009, // assign your own port no
    logs: "uat",
    applicationUrl: "http://20.121.222.211/",
    apiUrl: "http://emate-uat.ics-global.in:64460",
    emailPath: "./src/views",
    mongoUri: "mongodb+srv://intech:intech@cluster0.pmudmeh.mongodb.net/Toolkit_UAT",
    // mongoUri : "mongodb://emate:emate123@ec2-23-20-238-242.compute-1.amazonaws.com:27018/emate_toolkit_UAT?readPreference=primary&authMechanism=DEFAULT&authSource=admin",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "email.alert@ics-global.in",
    SMTP_PASS: "Desire$gnr@T3",
    SMTP_FROM_NAME: "Emate",
    SMTP_FROM_EMAIL: "info@emate.com",
    uploadFilePath: "/usr/src/app/src/public/upload/",
    uploadHelpFilePath: "/usr/src/app/src/public/helpModule/",
    uploadSampleFilePath: "/usr/src/app/src/public/sampleFiles",
    uploadFileUrl: "http://emate-uat.ics-global.in:64460/upload/",
    uploadHelpFileUrl :"http://emate-uat.ics-global.in:64460/helpPage/",
    excelFileUploadPath: "/usr/src/app/src/public/excelFiles",
    reportFolderPath: "./src/public/reports",
    reportFileUrl: "http://emate-uat.ics-global.in:64460/report/",
    sampleFileUrl: "http://emate-uat.ics-global.in:64460/sampleFile/",
    networkComputationStaticHTMLFile: "./src/templates/networkComputationReportTemplate.html",
    networkComputationHighChartHTMLFile: "./src/templates/highChartNC.html",
    portRatorStaticHTMLFile: "./src/templates/portRatorReportTemplate.html",
    forecastHTMLFile: "./src/templates/forecast.html",
  },

  pre_staging: {
    port: 4009, // assign your own port no
    logs: "dev",
    uploadFilePath: "/var/www/pre_staging/digital_business_card/dist/public/upload/",
    filePath: "http://20.121.222.211:4006/upload/upload/",
    applicationUrl: "http://20.121.222.211/",
    emailPath: "views",
    mongoUri: "mongodb+srv://mongouser:LNCzhjoLmDYH7Kqu@cluster0.tamah.mongodb.net/business_card_pre_staging?authSource=admin&replicaSet=atlas-93b547-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "email.alert@ics-global.in",
    SMTP_PASS: "Desire$gnr@T3",
    SMTP_FROM_NAME: "Emate",
    SMTP_FROM_EMAIL: "info@emate.com",
  },

  // production: {
  //   port: 4009, // assign your own port no
  //   logs: "dev",
  //   uploadFilePath: '/var/www/production/digital_business_card/dist/public/upload/',
  //   filePath: "https://bcapp.ics-global.in/upload/upload/",
  //   applicationUrl: 'https://bcfront.ics-global.in/',
  //   emailPath: "views",
  //   mongoUri: "mongodb://emate:emate123@ec2-23-20-238-242.compute-1.amazonaws.com:27018/emate_toolkit_production?readPreference=primary&authMechanism=DEFAULT&authSource=admin",
  //   SMTP_HOST: "smtp.gmail.com",
  //   SMTP_PORT: 587,
  //   SMTP_USER: "email.alert@ics-global.in",
  //   SMTP_PASS: "Desire$gnr@T3",
  //   SMTP_FROM_NAME: "Emate",
  //   SMTP_FROM_EMAIL: "info@emate.com",
  // },

  production: {
    port: 4009, // assign your own port no
    logs: "dev",
    applicationUrl: "http://20.121.222.211/",
    apiUrl: "https://api.etoolkit.app",
    mongoUri: "mongodb://emate:emate123@ec2-23-20-238-242.compute-1.amazonaws.com:27018/emate_toolkit_production?readPreference=primary&authMechanism=DEFAULT&authSource=admin",
    SMTP_HOST: "smtp.gmail.com",
    SMTP_PORT: 587,
    SMTP_USER: "email.alert@ics-global.in",
    SMTP_PASS: "Desire$gnr@T3",
    SMTP_FROM_NAME: "Emate",
    SMTP_FROM_EMAIL: "info@emate.com",
    uploadFilePath: "/usr/src/app/src/public/upload/",
    uploadSampleFilePath: "/usr/src/app/src/public/sampleFiles",
    uploadFileUrl: "https://api.etoolkit.app/upload/",
    uploadHelpFileUrl :"https://api.etoolkit.app/helpPage/",
    uploadHelpFilePath: "/usr/src/app/src/public/helpModule/",
    excelFileUploadPath: "/usr/src/app/src/public/excelFiles",
    reportFolderPath: "./src/public/reports",
    reportFileUrl: "https://api.etoolkit.app/report/",
    sampleFileUrl: "https://api.etoolkit.app/sampleFile/",
    networkComputationStaticHTMLFile: "./src/templates/networkComputationReportTemplate.html",
    networkComputationHighChartHTMLFile: "./src/templates/highChartNC.html",
    portRatorStaticHTMLFile: "./src/templates/portRatorReportTemplate.html",
    forecastHTMLFile: "./src/templates/forecast.html",
  },

  test: {
    // port: 4003,
    // logs: 'dev',
  },
};
