module.exports = {
  errorMessage: {
    genericError: "Something went wrong, please try again.",
    dataNotFound: "Data Not Found",
    tokenNotFound: "Token expire or not found",
    emailAlreadyExists: "E-Mail is already exists",
    findAccount: "You already have an account, Please login",
    wrongEmail: "No account exist with this email address",
    wrongEmailPassword: "Please enter valid email and password",
    wrongUsernamePassword: "Please enter valid User Name and password",
    verifyAccount: "Please verify your account",
    unRegistered: "Please register your self to login.!",
    doSocialLogin: "Please log in with your Social Account.",
    invalidVerification: "The link is expired or invalid",
    resetPasswordLinkExpire: "Reset password link expired, please try again",
    contactNotAllowed: "You're not allowed to add this contact.",
    userNotFound: "User not found.!",
    cantUpdateUser: "Sorry!, Can't update yours profile",
    requestFailed: "Failed to upload voice notes, Please try again",
    createPassword: "Please create a password to log in.",
    notRegistered: "Please register your self first.",
    notFound: "Not Found.!",
    canNotDeleteTopic: "Please remove all tools to delete this toolbox",
    canNotDeleteSubTopic: "Please remove tools to delete this sub-toolbox",
    emptyTree: "Decision tree can not be empty!",
    treeNotFound: "Data Not Found",
    treeExist: "Decision Tree is already available for this tool",
    treeNotFoundForQuestion: "Decision tree not found for this tool",
    topicAlreadyExist: "Toolbox already exist",
    subTopicAlreadyExist: "Sub toolbox already exist",
    questionAlreadyExist: "Tool already exist",
    unAuthorized: "Unauthorized request!",
    incorrectOldPassword: "Old password is incorrect",
    notValidEquation: "Please enter a valid equation",
    notCreateTreeWithStartAndEndNode: "Can not create decision tree only with start and end node",
    invalidOtp: "Invalid OTP",
    fileMissing: "Required excel file is missing",
    requiredFieldsMissing: "Required fields are missing",
    treeNotExist: "Decision Tree is not available for this tool!",
    fileHasNoData: "File has no data",
    invalidUpdateRequest: "Invalid Update Request",
    treeNotFoundForProcess: "Decision Tree not found for this process",
    notNullError: "Field can not be empty",
    preDefinedLogicNotFound : "Process Not Found",
    processAssignedToDecisionTree : "Logic is assigned to decision tree",
    headersValuesNotMatched: "Headers values are not matched with uplaoded multiple sheets",
    blankFileUploadedError: "Sorry, Uploaded file is empty/blank.",
    duplicatedUniqueValuesError: "Sorry, We getting duplicated unique values are in uploaded file",
    existingDuplicatedValuesError: "Sorry, We found some duplicated records with exists records",
    invalidRequestDetails: "Can not proceed request due to invalid request details",
    invalidPageDetails: "Sorry, This Page Does not exist",
    userNotFound: "User not found.!"
  },
  InfoMessage: {
    adminRegister: "admin created successfully!",
    adminLogin: "login successfully!",
    organizationCreated: "Organization created successfully!",
    updateOrganization: "Organization updated successfully!",
    organizationGet: "Organization get successfully!",
    topicCreated: "Toolbox created successfully!",
    topicUpdated: "Toolbox updated successfully!",
    subTopicCreated: "Sub-Toolbox created successfully!",
    topicGet: "Toolbox Get successfully!",
    deleteTopic: "Toolbox deleted successfully!",
    subTopicUpdated: "Sub-Toolbox update successfully!",
    subTopicGet: "Sub-Toolbox get successfully!",
    deleteSubTopic: "Sub-Toolbox deleted successfully!",
    questionCreated: "Tool created successfully!",
    questionUpdated: "Tool updated successfully!",
    questionDeleted: "Tool deleted successfully!",
    decisionTreeCreated: "Decision Tree Created successfully!",
    nodeDetails: "Node details get successfully!",
    inProgressTransaction: "User transaction is in progress!",
    transactionCompletedOrNotFound: "User transaction is completed or not yet started",
    savedTransaction: "User transaction created successfully!",
    createVariable: "Variable added successfully!",
    getVariable: "Variable List fetch successfully!",
    createFunction: "Function added successfully!",
    getFunction: "Function List fetch successfully!",
    userEmailAlreadyExist: "An user is already associated with this email address",
    userCreated: "User created successfully!",
    userUpdated: "User updated successfully!",
    userPasswordUpdated: "User password updated successfully!",
    userGet: "User Get successfully!",
    deleteUser: "User deleted successfully!",
    getTemplateDetail: "Node details get successfully!",
    getDecisionTree: "tree details get successfully!",
    stateGet: "State list get successfully!",
    productGet: "Product list get successfully!",
    productsUploaded: "Products has been uploaded successfully!",
    statesUploaded: "States has been uploaded successfully!",
    sitesUploaded: "Sites has been uploaded successfully!",
    mileageUploaded: "Mileage has been uploaded successfully!",
    ltrRatesUploaded: "LTR Rates has been uploaded successfully!",
    trailerSizesUploaded: "Trailer sizes has been uploaded successfully!",
    siteGet: "Site list get successfully!",
    parselRatesUploaded: "Parsel Rates has been uploaded successfully!",
    parselRaterProcessDone: "Parsel Rater process done successfully!",
    multiSelectorList: "Multi selector list get successfully!",
    multiSelectorCreated: "Multi selector created successfully!",
    preDefinedLogicList: "Pre-defined logic list get successfully!",
    predefinedLogicGet : "Logic get successfully!",
    processUpdate : "Pre-defined process updated successfully!",
    preDefinedLogicCreated: "Pre-defined created successfully!",
    predefinedRaterProcessDone: "Pre-defined Rater process done successfully!",
    predefinedRaterProcessInputMissing: "Please provide atleast one input percentage",
    predefinedRaterProcessTotalPercent: "Total of all the inputs percentage should be 100",
    allSheetUploaded: "All the excel sheets uploaded successfully!",
    fileUploaded: "File uploaded successfully!",
    fileDeleted: "File deleted successfully!",
    dataUpdated: "Data updated successfully!",
    filesGet: "Files Get successfully!",
    dataGet: "Data Get successfully!",
    excelSheetUploadError: "There are some issues with uploading excel files",
    reportGenerate: "Report generated successfully!",
    reportNotFound: "Report not found",
    completedTransaction: "Transaction added successfully!",
    updateDecisionTree: "DecisionTree updated successfully!",
    deleteDecisionTree: "DecisionTree deleted successfully!",
    dashboardDetails: "Dashboard details fetch successfully!",
    userNotFound: "User details not found",
    organizationNotFound: "Organization details not found",
    profileGet: "Profile Get successfully!",
    profileOrganizationGet: "Profile Organization Get successfully!",
    otpSendOnEmail: "OTP has been sent on provided email address",
    changePasswordSuccess: "Password has been changed successfully",
    getOperatorList: "Operator list get successfully!",
    getReportTemplateList: "Report templates list successfully!",
    processDelete : "Pre-defined process deleted successfully!",
    updateReportTemplate : "report template updated successfully!",
    cloneTool : "Tool cloned successfully!",
    fileUpdated : "File updated successfully!",
    getUrl : "file download successfully!",
    getTypeList : "Type fetch successfully!",
    getFormatList : "Formats get successfully!",
    getHelpList : "Help Module List Fetched successfully!",
    helpGet: "Page info Get successfully!",
    pageInfoUpdated : "Page Info updated successfully!",
    deletedSuccessfully: "Your Account is deleted successfully",
  },
  emails: {},
};
